openapi: 3.0.0
info:
  title: AlfabetizaPlus API
  version: "1.0.0"
  description: >-
    Contrato da API AlfabetizaPlus descrevendo os recursos expostos pelo backend
    Spring Boot. Todas as rotas listadas abaixo estão prefixadas com `/api` no
    ambiente de produção.
servers:
  - url: https://{host}/api
    variables:
      host:
        default: 191.253.23.111:8080
security:
  - bearerAuth: []
tags:
  - name: Autenticação
    description: Fluxo de registro e consulta do usuário autenticado via Firebase.
  - name: Usuários
    description: Recursos relacionados aos dados do usuário autenticado.
  - name: Conteúdo pedagógico
    description: Estrutura de unidades, aulas, atividades e práticas do aplicativo.
  - name: Conquistas
    description: Consulta de conquistas disponíveis e status para o usuário.
  - name: Gamificação
    description: Operações relacionadas a moedas, chaves e vidas do usuário.
  - name: Respostas
    description: Registro das respostas do usuário e impacto na gamificação.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    AuthHeader:
      name: Authorization
      in: header
      required: true
      description: Token JWT (Firebase ID Token) no formato `Bearer <token>`.
      schema:
        type: string
    GoogleUidQuery:
      name: googleUid
      in: query
      required: true
      description: Identificador único do usuário no Firebase.
      schema:
        type: string
  schemas:
    UsuarioDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - nome
        - email
    UsuarioDetalhe:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        email:
          type: string
          format: email
        googleUid:
          type: string
        dataCriacao:
          type: string
          format: date-time
        gamificacao:
          $ref: '#/components/schemas/Gamificacao'
      required:
        - id
        - nome
        - email
        - googleUid
        - dataCriacao
    Gamificacao:
      type: object
      properties:
        id:
          type: integer
          format: int64
        moedas:
          type: integer
          minimum: 0
        chaves:
          type: integer
          minimum: 0
        vidas:
          type: integer
          minimum: 0
      required:
        - id
        - moedas
        - chaves
        - vidas
    GamificacaoDTO:
      type: object
      properties:
        moedas:
          type: integer
          minimum: 0
        chaves:
          type: integer
          minimum: 0
        vidas:
          type: integer
          minimum: 0
      required:
        - moedas
        - chaves
        - vidas
    ProgressoResumoDTO:
      type: object
      properties:
        percentualConclusao:
          type: number
          format: float
          minimum: 0
          maximum: 100
        completou:
          type: boolean
      required:
        - percentualConclusao
        - completou
    UnidadeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        descricao:
          type: string
        imagemUrl:
          type: string
          format: uri
        progressoUsuario:
          $ref: '#/components/schemas/ProgressoResumoDTO'
      required:
        - id
        - nome
        - descricao
    AulaDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        descricao:
          type: string
      required:
        - id
        - nome
        - descricao
    AtividadeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        descricao:
          type: string
      required:
        - id
        - nome
        - descricao
    RespostaPossivelDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        descricao:
          type: string
        imagem:
          type: string
          format: uri
      required:
        - id
        - descricao
    PraticaDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        descricao:
          type: string
        imagem:
          type: string
          format: uri
        respostas:
          type: array
          items:
            $ref: '#/components/schemas/RespostaPossivelDTO'
      required:
        - id
        - descricao
        - respostas
    ConquistaDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        descricao:
          type: string
        iconeUrl:
          type: string
          format: uri
        conquistada:
          type: boolean
      required:
        - id
        - nome
        - descricao
        - conquistada
paths:
  /auth/register:
    post:
      tags:
        - Autenticação
      summary: Registrar ou carregar usuário autenticado
      description: >-
        Registra o usuário autenticado via Firebase caso ainda não exista e
        retorna seus dados básicos.
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
      responses:
        '200':
          description: Usuário registrado ou recuperado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioDTO'
        '401':
          description: Token inválido ou expirado.
  /auth/me:
    get:
      tags:
        - Autenticação
      summary: Buscar dados básicos do usuário autenticado
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
      responses:
        '200':
          description: Dados básicos do usuário associado ao token informado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioDTO'
        '401':
          description: Token inválido ou expirado.
  /usuarios/me:
    get:
      tags:
        - Usuários
      summary: Obter dados completos do usuário autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dados completos do usuário autenticado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioDetalhe'
        '401':
          description: Usuário não autenticado ou token inválido.
  /unidades:
    get:
      tags:
        - Conteúdo pedagógico
      summary: Listar unidades disponíveis
      parameters:
        - $ref: '#/components/parameters/GoogleUidQuery'
      responses:
        '200':
          description: Lista de unidades com progresso do usuário.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UnidadeDTO'
        '404':
          description: Usuário não encontrado.
  /unidades/{idUnidade}/aulas:
    get:
      tags:
        - Conteúdo pedagógico
      summary: Listar aulas de uma unidade
      parameters:
        - name: idUnidade
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Lista de aulas da unidade informada.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AulaDTO'
        '404':
          description: Unidade não encontrada.
  /aulas/{idAula}/atividades:
    get:
      tags:
        - Conteúdo pedagógico
      summary: Listar atividades de uma aula
      parameters:
        - name: idAula
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Lista de atividades da aula.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AtividadeDTO'
        '404':
          description: Aula não encontrada.
  /atividades/{idAtividade}/praticas:
    get:
      tags:
        - Conteúdo pedagógico
      summary: Listar práticas de uma atividade
      parameters:
        - name: idAtividade
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Práticas vinculadas à atividade informada.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PraticaDTO'
        '404':
          description: Atividade não encontrada.
  /praticas/{idPratica}:
    get:
      tags:
        - Conteúdo pedagógico
      summary: Buscar detalhes de uma prática
      parameters:
        - name: idPratica
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Detalhes da prática solicitada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PraticaDTO'
        '404':
          description: Prática não encontrada.
  /conquistas:
    get:
      tags:
        - Conquistas
      summary: Listar conquistas do usuário
      parameters:
        - $ref: '#/components/parameters/GoogleUidQuery'
      responses:
        '200':
          description: Lista de conquistas e o status do usuário informado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConquistaDTO'
        '404':
          description: Usuário não encontrado.
  /gamificacao/me:
    get:
      tags:
        - Gamificação
      summary: Obter estado de gamificação do usuário autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Estado atual da gamificação.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamificacaoDTO'
        '401':
          description: Usuário não autenticado ou token inválido.
  /gamificacao/add-moedas/{quantidade}:
    post:
      tags:
        - Gamificação
      summary: Adicionar moedas ao usuário autenticado
      security:
        - bearerAuth: []
      parameters:
        - name: quantidade
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Gamificação atualizada após adicionar moedas.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamificacaoDTO'
        '401':
          description: Usuário não autenticado ou token inválido.
  /gamificacao/perder-vida:
    post:
      tags:
        - Gamificação
      summary: Remover uma vida do usuário autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Gamificação atualizada após perder uma vida.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamificacaoDTO'
        '401':
          description: Usuário não autenticado ou token inválido.
  /respostas/{idPratica}/responder:
    post:
      tags:
        - Respostas
      summary: Registrar resposta do usuário a uma prática
      security:
        - bearerAuth: []
      parameters:
        - name: idPratica
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: idResposta
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Mensagem indicando o resultado da resposta.
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Usuário não autenticado ou token inválido.
        '404':
          description: Prática ou resposta informada não encontrada.
