CREATE TABLE atividade
(
    id_atividade BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_aula      BIGINT                                  NOT NULL,
    nome         VARCHAR(150)                            NOT NULL,
    descricao    TEXT,
    CONSTRAINT pk_atividade PRIMARY KEY (id_atividade)
);

CREATE TABLE aula
(
    id_aula    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_unidade BIGINT                                  NOT NULL,
    nome       VARCHAR(150)                            NOT NULL,
    descricao  TEXT,
    CONSTRAINT pk_aula PRIMARY KEY (id_aula)
);

CREATE TABLE gamificacao
(
    id_gamificacao BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario     BIGINT                                  NOT NULL,
    moedas         INTEGER,
    chaves         INTEGER,
    vidas          INTEGER,
    CONSTRAINT pk_gamificacao PRIMARY KEY (id_gamificacao)
);

CREATE TABLE pratica
(
    id_pratica   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_atividade BIGINT                                  NOT NULL,
    descricao    TEXT                                    NOT NULL,
    imagem       VARCHAR(255),
    CONSTRAINT pk_pratica PRIMARY KEY (id_pratica)
);

CREATE TABLE progresso_usuario
(
    id_progresso         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario           BIGINT                                  NOT NULL,
    id_unidade           BIGINT,
    id_aula              BIGINT                                  NOT NULL,
    id_atividade         BIGINT,
    concluida            BOOLEAN                                 NOT NULL,
    data_conclusao       TIMESTAMP WITHOUT TIME ZONE,
    percentual_conclusao DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_progresso_usuario PRIMARY KEY (id_progresso)
);

CREATE TABLE resposta_possivel
(
    id_resposta BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_pratica  BIGINT                                  NOT NULL,
    descricao   VARCHAR(255)                            NOT NULL,
    imagem      VARCHAR(255),
    correta     BOOLEAN,
    CONSTRAINT pk_resposta_possivel PRIMARY KEY (id_resposta)
);

CREATE TABLE resposta_usuario
(
    id_resposta_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario          BIGINT                                  NOT NULL,
    id_pratica          BIGINT                                  NOT NULL,
    id_resposta         BIGINT                                  NOT NULL,
    data_resposta       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_resposta_usuario PRIMARY KEY (id_resposta_usuario)
);

CREATE TABLE unidade
(
    id_unidade BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(150)                            NOT NULL,
    descricao  TEXT,
    imagem_url VARCHAR(500),
    CONSTRAINT pk_unidade PRIMARY KEY (id_unidade)
);

CREATE TABLE usuario
(
    id_usuario   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(100)                            NOT NULL,
    email        VARCHAR(150)                            NOT NULL,
    google_uid   VARCHAR(255)                            NOT NULL,
    data_criacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario)
);

ALTER TABLE gamificacao
    ADD CONSTRAINT uc_gamificacao_id_usuario UNIQUE (id_usuario);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_email UNIQUE (email);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_google_uid UNIQUE (google_uid);

ALTER TABLE atividade
    ADD CONSTRAINT FK_ATIVIDADE_ON_ID_AULA FOREIGN KEY (id_aula) REFERENCES aula (id_aula);

ALTER TABLE aula
    ADD CONSTRAINT FK_AULA_ON_ID_UNIDADE FOREIGN KEY (id_unidade) REFERENCES unidade (id_unidade);

ALTER TABLE gamificacao
    ADD CONSTRAINT FK_GAMIFICACAO_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE pratica
    ADD CONSTRAINT FK_PRATICA_ON_ID_ATIVIDADE FOREIGN KEY (id_atividade) REFERENCES atividade (id_atividade);

ALTER TABLE progresso_usuario
    ADD CONSTRAINT FK_PROGRESSO_USUARIO_ON_ID_ATIVIDADE FOREIGN KEY (id_atividade) REFERENCES atividade (id_atividade);

ALTER TABLE progresso_usuario
    ADD CONSTRAINT FK_PROGRESSO_USUARIO_ON_ID_AULA FOREIGN KEY (id_aula) REFERENCES aula (id_aula);

ALTER TABLE progresso_usuario
    ADD CONSTRAINT FK_PROGRESSO_USUARIO_ON_ID_UNIDADE FOREIGN KEY (id_unidade) REFERENCES unidade (id_unidade);

ALTER TABLE progresso_usuario
    ADD CONSTRAINT FK_PROGRESSO_USUARIO_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE resposta_possivel
    ADD CONSTRAINT FK_RESPOSTA_POSSIVEL_ON_ID_PRATICA FOREIGN KEY (id_pratica) REFERENCES pratica (id_pratica);

ALTER TABLE resposta_usuario
    ADD CONSTRAINT FK_RESPOSTA_USUARIO_ON_ID_PRATICA FOREIGN KEY (id_pratica) REFERENCES pratica (id_pratica);

ALTER TABLE resposta_usuario
    ADD CONSTRAINT FK_RESPOSTA_USUARIO_ON_ID_RESPOSTA FOREIGN KEY (id_resposta) REFERENCES resposta_possivel (id_resposta);

ALTER TABLE resposta_usuario
    ADD CONSTRAINT FK_RESPOSTA_USUARIO_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);