CREATE TABLE conquista
(
    id_conquista      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome              VARCHAR(150)                            NOT NULL,
    descricao         TEXT,
    icone_url         VARCHAR(500),
    recompensa_moedas INTEGER                                 NOT NULL,
    CONSTRAINT pk_conquista PRIMARY KEY (id_conquista)
);

CREATE TABLE conquista_aula
(
    id_aula      BIGINT NOT NULL,
    id_conquista BIGINT NOT NULL
);

CREATE TABLE conquista_usuario
(
    id_conquista_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario           BIGINT                                  NOT NULL,
    id_conquista         BIGINT                                  NOT NULL,
    data_conquista       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_conquista_usuario PRIMARY KEY (id_conquista_usuario)
);

ALTER TABLE conquista_usuario
    ADD CONSTRAINT FK_CONQUISTA_USUARIO_ON_ID_CONQUISTA FOREIGN KEY (id_conquista) REFERENCES conquista (id_conquista);

ALTER TABLE conquista_usuario
    ADD CONSTRAINT FK_CONQUISTA_USUARIO_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE conquista_aula
    ADD CONSTRAINT fk_conaul_on_aula FOREIGN KEY (id_aula) REFERENCES aula (id_aula);

ALTER TABLE conquista_aula
    ADD CONSTRAINT fk_conaul_on_conquista FOREIGN KEY (id_conquista) REFERENCES conquista (id_conquista);
CREATE TABLE conquista
(
    id_conquista      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome              VARCHAR(150)                            NOT NULL,
    descricao         TEXT,
    icone_url         VARCHAR(500),
    recompensa_moedas INTEGER                                 NOT NULL,
    CONSTRAINT pk_conquista PRIMARY KEY (id_conquista)
);

CREATE TABLE conquista_aula
(
    id_aula      BIGINT NOT NULL,
    id_conquista BIGINT NOT NULL
);

CREATE TABLE conquista_usuario
(
    id_conquista_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario           BIGINT                                  NOT NULL,
    id_conquista         BIGINT                                  NOT NULL,
    data_conquista       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_conquista_usuario PRIMARY KEY (id_conquista_usuario)
);

ALTER TABLE atividade
    ADD video_apresentacao_url VARCHAR(500);

ALTER TABLE atividade
    ADD video_instrucao_url VARCHAR(500);

ALTER TABLE conquista_usuario
    ADD CONSTRAINT FK_CONQUISTA_USUARIO_ON_ID_CONQUISTA FOREIGN KEY (id_conquista) REFERENCES conquista (id_conquista);

ALTER TABLE conquista_usuario
    ADD CONSTRAINT FK_CONQUISTA_USUARIO_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE conquista_aula
    ADD CONSTRAINT fk_conaul_on_aula FOREIGN KEY (id_aula) REFERENCES aula (id_aula);

ALTER TABLE conquista_aula
    ADD CONSTRAINT fk_conaul_on_conquista FOREIGN KEY (id_conquista) REFERENCES conquista (id_conquista);